
from deepagent.config import config
from deepagent.models.agent_schemas import ContextData, Issue, ReconciledReview


def _severity_emoji(severity: str) -> str:
    return {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(severity, "⚪")


def _render_issue(issue: Issue) -> list[str]:
    lines = [
        f"- {_severity_emoji(issue.severity)} **[{issue.category}] {issue.title}**"
        f" — `{issue.file}`:{issue.line_start}",
        f"  {issue.description}",
    ]
    if issue.suggestion:
        lines.append(f"  **Fix**: {issue.suggestion}")
    return lines


def format_github_comment(
    review: ReconciledReview,
    context: ContextData | None,
    pr_number: int,
) -> str:
    """Format a ReconciledReview + ContextData into a structured GitHub comment."""
    parts: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────
    parts.append("## 🐍 BugViper AI Code Review")
    parts.append("")
    parts.append(f"**PR**: #{pr_number} | **Model**: {config.review_model}")
    parts.append("")
    parts.append(f"**{review.summary}**")
    parts.append("")
    parts.append("---")
    parts.append("")

    # ── Impact analysis ───────────────────────────────────────────────────
    if context:
        risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(context.risk_level, "⚪")
        parts.append("### 📊 Impact Analysis")
        parts.append("")
        parts.append(f"- **Symbols modified**: {len(context.modified_symbols)}")
        parts.append(f"- **Downstream callers**: {context.total_callers}")
        parts.append(f"- **Risk level**: {risk_emoji} {context.risk_level.upper()}")
        parts.append("")
        parts.append("---")
        parts.append("")

    # Bucket issues by status
    fixed_issues   = [i for i in review.issues if i.status == "fixed"]
    open_issues    = [i for i in review.issues if i.status == "still_open"]
    new_issues     = [i for i in review.issues if i.status == "new"]

    # ── Fixed ─────────────────────────────────────────────────────────────
    if fixed_issues:
        parts.append("### ✅ Fixed Since Last Review")
        parts.append("")
        for issue in fixed_issues:
            parts.append(f"- ~~**{issue.title}**~~ in `{issue.file}` — resolved")
        parts.append("")

    # ── Still open ────────────────────────────────────────────────────────
    if open_issues:
        parts.append("### 🔁 Still Open")
        parts.append("")
        for issue in open_issues:
            for line in _render_issue(issue):
                parts.append(line)
        parts.append("")

    # ── New issues ────────────────────────────────────────────────────────
    if new_issues:
        parts.append("### 🆕 New Issues This Run")
        parts.append("")
        critical = [i for i in new_issues if i.severity == "critical"]
        high     = [i for i in new_issues if i.severity == "high"]
        medium   = [i for i in new_issues if i.severity == "medium"]
        low      = [i for i in new_issues if i.severity == "low"]

        for group_label, group in [
            ("🔴 Critical", critical),
            ("🟠 High", high),
            ("🟡 Medium", medium),
            ("🟢 Low", low),
        ]:
            if group:
                parts.append(f"#### {group_label}")
                for issue in group:
                    for line in _render_issue(issue):
                        parts.append(line)
                parts.append("")

    if not fixed_issues and not open_issues and not new_issues:
        parts.append("✅ **No issues found!**")
        parts.append("")

    # ── Positive findings ─────────────────────────────────────────────────
    if review.positive_findings:
        parts.append("### 👍 Positive Findings")
        for finding in review.positive_findings:
            parts.append(f"- {finding}")
        parts.append("")

    # ── Footer ────────────────────────────────────────────────────────────
    parts.append("---")
    parts.append("")
    parts.append(f"*🤖 Generated by BugViper | Powered by {config.review_model}*")

    return "\n".join(parts)
