"""Format review results into a GitHub PR comment."""

from deepagent.config import config
from deepagent.models.agent_schemas import ContextData, ReviewResults


def format_github_comment(
    review_results: ReviewResults,
    context: ContextData | None,
    pr_number: int,
) -> str:
    """Format ReviewResults + ContextData into a markdown GitHub comment."""
    parts: list[str] = []

    # Header
    parts.append("## 🐍 BugViper AI Code Review")
    parts.append("")
    parts.append(f"**PR**: #{pr_number}")
    parts.append(f"**Model**: {config.review_model}")
    parts.append("")
    parts.append("---")
    parts.append("")

    # Impact analysis
    if context:
        parts.append("### 📊 Impact Analysis")
        parts.append("")
        parts.append(f"- **Symbols modified**: {len(context.modified_symbols)}")
        parts.append(f"- **Downstream callers**: {context.total_callers}")
        risk_emoji = {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(context.risk_level, "⚪")
        parts.append(f"- **Risk level**: {risk_emoji} {context.risk_level.upper()}")
        parts.append("")
        parts.append("---")
        parts.append("")

    # Review findings
    issues = review_results.issues
    parts.append("### 🔍 Code Review")
    parts.append("")
    parts.append(f"**Summary**: {review_results.summary}")
    parts.append("")

    if issues:
        critical = [i for i in issues if i.severity == "critical"]
        high = [i for i in issues if i.severity == "high"]
        medium = [i for i in issues if i.severity == "medium"]
        low = [i for i in issues if i.severity == "low"]

        if critical:
            parts.append("#### 🔴 Critical Issues")
            for issue in critical:
                parts.append(f"- **[{issue.category}]** {issue.title}")
                parts.append(f"  - File: `{issue.file}`:{issue.line_start}")
                parts.append(f"  - {issue.description}")
                if issue.suggestion:
                    parts.append(f"  - **Fix**: {issue.suggestion}")
            parts.append("")

        if high:
            parts.append("#### 🟠 High Priority Issues")
            for issue in high:
                parts.append(f"- **{issue.title}** in `{issue.file}`:{issue.line_start}")
                parts.append(f"  - {issue.description}")
                if issue.suggestion:
                    parts.append(f"  - **Fix**: {issue.suggestion}")
            parts.append("")

        if medium:
            parts.append("#### 🟡 Medium Priority Issues")
            for issue in medium:
                parts.append(f"- **{issue.title}** in `{issue.file}`:{issue.line_start}")
                parts.append(f"  - {issue.description}")
                if issue.suggestion:
                    parts.append(f"  - **Fix**: {issue.suggestion}")
            parts.append("")

        if low:
            parts.append("#### 🟢 Low Priority Issues")
            for issue in low:
                parts.append(f"- {issue.title} in `{issue.file}`:{issue.line_start}")
            parts.append("")
    else:
        parts.append("✅ **No issues found!**")
        parts.append("")

    if review_results.positive_findings:
        parts.append("#### ✅ Positive Findings")
        for finding in review_results.positive_findings:
            parts.append(f"- {finding}")
        parts.append("")

    # Footer
    parts.append("---")
    parts.append("")
    parts.append("*🤖 Generated by BugViper (PydanticAI)*")
    parts.append(f"*Powered by {config.review_model}*")

    return "\n".join(parts)
